#!/usr/bin/env php
<?php

foreach ([__DIR__.'/../autoload.php', __DIR__.'/../../autoload.php', __DIR__.'/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        $autoload = $file;

        break;
    }
}

if (! isset($autoload) || ! file_exists($autoload)) {
    fwrite(STDERR, 'Autoload not found'.PHP_EOL);

    die(1);
}

require $autoload;

$composer = new HuangYi\Shadowfax\Composer($autoload);

$shadowfax = new HuangYi\Shadowfax\Shadowfax(
    $_ENV['SHADOWFAX_BASE_PATH'] ?? __DIR__
);

$shadowfax->instance(HuangYi\Shadowfax\Composer::class, $composer);

$shadowfax->addCommands([
    new HuangYi\Shadowfax\Console\StartCommand,
    new HuangYi\Shadowfax\Console\StopCommand,
    new HuangYi\Shadowfax\Console\ReloadCommand,
]);

unset($autoload, $composer);

$shadowfax->run();
