#!/usr/bin/env php
<?php

foreach ([
    __DIR__ . '/vendor/phpunit/phpunit/phpunit',
    __DIR__ . '/../../phpunit/phpunit/phpunit',
    __DIR__ . '/../vendor/phpunit/phpunit/phpunit',
] as $file) {
    if (file_exists($file)) {
        $phpunit = $file;

        break;
    }
}

unset($file);

if (! isset($phpunit)) {
    fwrite(
        STDERR,
        'Cannot find phpunit.' . PHP_EOL
    );

    die(1);
}

Swoole\Coroutine::create(function () use ($phpunit) {
    try{
        eval(str_replace(
            ["#!/usr/bin/env php\n<?php declare(strict_types=1);", '<?php'],
            '',
            file_get_contents($phpunit)
        ));
    } catch (Swoole\ExitException $e) {
        return;
    }
});
